//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-J8JE5C3;Initial Catalog=QL_VLXD;User ID=sa;Password=123;Encry" +
            "pt=True;TrustServerCertificate=True")]
        public string QL_VLXDConnectionString {
            get {
                return ((string)(this["QL_VLXDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-J8JE5C3;Initial Catalog=QL_VLXD;Persist Security Info=True;Us" +
            "er ID=sa;Password=123;TrustServerCertificate=True")]
        public string QL_VLXDConnectionString1 {
            get {
                return ((string)(this["QL_VLXDConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-6P25OEGD\\SQLSERVER;Initial Catalog=QL_VLXD;Integrated Security" +
            "=True;TrustServerCertificate=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HPMINHKHANG\\MKHANG;Initial Catalog=QL_VLXD;Persist Security Info=True" +
            ";User ID=sa;Password=123;TrustServerCertificate=True")]
>>>>>>> d0e984e1ab90c7fd50654ad9f9df81a431703718
        public string QL_VLXDConnectionString2 {
            get {
                return ((string)(this["QL_VLXDConnectionString2"]));
            }
        }
    }
}
